spring:
    datasource:
        url: ---

        username: ***
        password: ***
        driverClassName: org.postgresql.Driver

    flyway:
        enabled: true
        user: ***
        password: ***
        schemas: public
        url: ---


